### ISSUE TITLE
Symlinks are preserved when using 'cp -r'

### ISSUE THREAD

**Issue by vdel** [Deepomatic/dmake#107]
This may lead to errors when preparing the workspace to build, e.g. when a script file points to a shared install script. In this case, dmake tries to copy install scripts of the base image, but preserve the link when doing so. Of course the link become stale when considered in the isolated environment of the base image.

It's not clear we want to always deference symlinks however. For now `dmake_copy` is only used when building the base image, so changing it directly seems fine.

**Comment by thomas-riccardi** [comment]
We already dereference the symlinks when copying the workspace for service image build, it makes sense to also do that for the base image.
