### ISSUE TITLE
Allow to specify a Dockerfile to build a service

### ISSUE THREAD

**Issue by vdel** [Deepomatic/dmake#139]
(upon a base image as usal for now)

This will allow to build a service in multiple version, notably dev, prod, and embedded versions.

This would be an alternative to the `docker_image` field of a service. This is also a way to start transitioning to a build chain where artefacts are fully defined by dockerfiles, as discussed with @thomas-riccardi

**Comment by thomas-riccardi** [comment]
Future features could be:
- add `build.target`: useful for https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage : we could have one Dockerfile and multiple services stopping at different stages, reusing docker build cache
- add `build.cache_from`: could help the build cache somehow: https://medium.com/@gajus/making-docker-in-docker-builds-x2-faster-using-docker-cache-from-option-c01febd8ef84

**Comment by thomas-riccardi** [comment]
- `build.target`: #180
- `build.cache_from`: #181
