### ISSUE TITLE
Crash when running shell on a service needing GPU without nvidia-docker

### ISSUE THREAD

**Issue by vdel** [Deepomatic/dmake#157]
I pulled the last version of dmake and now running `dmake shell worker-nn:tf` leads to a crash:

```
## Deploying ##
- Running shell @ vulcain/worker-nn:tf
docker: Error response from daemon: Unknown runtime specified nvidia.
```

I do not have nvidia-docker installed which, I guess, is the problem. I would prefer to avoid installing it.

**Comment by thomas-riccardi** [comment]
As a dmake user you have explicitly opt-out of GPU, see https://github.com/Deepomatic/dmake/pull/141:
`export DMAKE_NO_GPU=1`: the services will be run without GPU, it could break things: it's the user's responsibility.

We could add a check and a more explicit warning including the workaround: https://github.com/Deepomatic/dmake/issues/158
