### ISSUE TITLE
`-d` option should be the default behavior: run dependencies by default

### ISSUE THREAD

**Issue by thomas-riccardi** [Deepomatic/dmake#211]
*not* running dependencies by default mean that we often use external services instead of local ones: users could accidentally break things remotely without even noticing.

Running with dependencies by default would avoid that, and correspond to most use-cases.

**Comment by maingoh** [comment]
Just, i often don't want all the depandancies because it takes too much time to start/build. So i am not sure i want to change the behavior.

**Comment by maingoh** [comment]
Probably yes. Lets discuss about it on monday
