### ISSUE TITLE
Dmake fail when there is a `#` or `/` in the branch name

### ISSUE THREAD

**Issue by Zorrette** [Deepomatic/dmake#23]
Docker gives a ``` invalid reference format ``` when launching Dmake in a branch with a ```#``` in the name.

**Comment by thomas-riccardi** [comment]
Related: when there are `/` in branch name it fails too, at docker build stage: (happened with dependabot)
```
+ dmake_build_docker xxx deepomatic/xxx:dependabot/npm_and_yarn/xxx/xxx-1.2.3 --file=xxx/./deploy/Dockerfile --build-arg=BASE_IMAGE=deepomatic/xxx:base-rid-sha256-xxx-d2-xxx
invalid argument "deepomatic/xxx:dependabot/npm_and_yarn/xxx/xxx-1.2.3" for "-t, --tag" flag: invalid reference format
See 'docker image build --help'.
```

**Comment by thomas-riccardi** [comment]
for uniqueness + determinism maybe:
- slugify: replace all unwanted characters by `-`
- append to slug a (truncated, maybe 6-8 chars?) hash of raw value

**Comment by thomas-riccardi** [comment]
Branch name is used in:
- docker image tag: [source](https://docs.docker.com/engine/reference/commandline/tag/#extended-description)
  > A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.
- docker volume name (for shared volumes): [source](https://github.com/moby/moby/blob/92cc603036ddadd608762a6f69e72b9b2bef651e/volume/local/local.go#L256), [source](https://github.com/moby/moby/blob/92cc603036ddadd608762a6f69e72b9b2bef651e/daemon/names/names.go#L6)
  > `[a-zA-Z0-9][a-zA-Z0-9_.-]`
- exported environment variables: no limitation there
- docker container names (notably for `dmake stop`)
- deployed versions git tags: ~[less restrictive than docker](https://stackoverflow.com/a/26382358)
- ssh deployment: deprecated, wontfix
- kubernetes deployment injected metadata: no limitation there
