### ISSUE TITLE
Allow variables in volume field

### ISSUE THREAD

**Issue by maingoh** [Deepomatic/dmake#259]
I want to use the named volume feature which seem to work only with `volumes` field (not `data_volumes`). I would like that the container path is an env variable, but dmake evaluate it after the check that it starts with a `/` to be an absolute path : 
```
# this doesn't work
volumes:
    - mynamedvolume: ${MY_DIR}
```

`data_volumes` allows to use env variables but doens't seem to handle named volumes ? I need both :)

Also maybe we should merge those two fields ?

**Comment by thomas-riccardi** [comment]
Ideally yes, `data_volumes` and `volumes` should be merged.
Same for docker_links and services...

`data_volumes` and `volumes` have another difference: `volumes` with paths (not named/shared volumes) are not always mounted, depending on dmake command (shell vs test)...

So for now if I understand correctly you need shared volumes with `target` validation done *after* variable expansion, as done by `data_volumes`.

The check is done here: https://github.com/Deepomatic/dmake/blob/79ced868ec4c6030965cb924df8132a13d2c8c1b/dmake/deepobuild.py#L202-L203 at yaml validation time. It should check for `/` or `$`, and add a second, final check at execution time.

Also, after reading the code *there is no variable expansion* done for shared volume `target`. This feature needs to be added too.
