### ISSUE TITLE
Dependency between services is not working properly

### ISSUE THREAD

**Issue by vdel** [Deepomatic/dmake#55]
If service A needs B and B has changed, A is not re-tested whereas it should be.

**Comment by vdel** [comment]
For example, if you modify worker-nn in Vulcan, it should trigger tests for the API.
But if you leave DMAKE_APP empty (instead of `*`), here is what dmake does:

```
Here is the plan:
## Building Base ##
- base @ deepomatic/vulcain-api::base
- base @ smyle/maya-workers-base::base
## Building App ##
- build_docker @ vulcain/init-db
- build_docker @ vulcain/worker-nn
## Testing App ##
- run_link @ links/vulcain/postgres
- run @ vulcain/init-db
- run_link @ links/vulcain/rabbitmq
- test @ vulcain/worker-nn
```

**Comment by vdel** [comment]
Here is an example of PR where a change in the worker-nn did not triggered a re-build of the api (which depends on it): https://github.com/Deepomatic/vulcan/pull/782

**Comment by thomas-riccardi** [comment]
Closing in favor of #55.
