### ISSUE TITLE
Multiple base image per `dmake.yml`

### ISSUE THREAD

**Issue by thomas-riccardi** [Deepomatic/dmake#75]
We should support multiple base image per `dmake.yml` file.

Starting from the deployment down to the root image:
- deploy a service
- service has one base image only
- duplicate services for multiple base image
- each service specifies its base image (with default value such as old dmake.yml still work) (chooses a base image, not a root, image, it should influence next step)
- relation between base and root: no idea yet

For developers/test multi base image services are just 2 different services, it seems to work great.

**Comment by bushibushi** [comment]
@thomas-riccardi Isn't there a confusion between base/root image ? For me it is multiple root images but unique base image.

**Comment by thomas-riccardi** [comment]
it doesn't work if it's different OS on the root image: we then cannot apply the same build steps for base image on top of root image.
